### ISSUE TITLE
Add space between styles header and styles in the exported/cloned theme

### ISSUE THREAD

**Issue by madhusudhand** [WordPress/create-block-theme#378]
When a theme is cloned, it creates following style definition.

```css
/*
Theme Name: George Lois
Theme URI: https://wordpress.com/theme/georgelois/
Author: Automattic
Author URI: https://wordpress.org/themes/
Description: A theme in homage to George Lois, visionary American Art Director, and author. We will all miss your big ideas. Rest in Peace, George. From the Creative People of Automattic.
Requires at least: 6.0
Tested up to: 6.2.1
Requires PHP: 5.7
Version: 0.0.1
License: GNU General Public License v2 or later
License URI: http://www.gnu.org/licenses/gpl-2.0.html
Text Domain: georgelois
Tags: two-columns, wide-blocks, custom-colors, custom-logo, custom-menu, editor-style, featured-images, full-site-editing, rtl-language-support, theme-options, threaded-comments, translation-ready, auto-loading-homepage
*//*
 * Control the hover stylings of outline block style.
 * Unnecessary once block styles are configurable via theme.json
 * https://github.com/WordPress/gutenberg/issues/42794
 */
.wp-block-button.is-style-outline>.wp-block-button__link:not(.has-background):hover {
	background-color: var(--wp--preset--color--secondary);
	color: var(--wp--preset--color--foreground);
	border-color: var(--wp--preset--color--secondary);
}
```

### Expectation

Add a new line between styles header and styles.
